name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install      
      - name: ESlint
        run: npm run eslint . --ext .js,.jsx,.ts,.tsx
        

